In [2]:
import numpy as np

In [3]:
#Q1

arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [8]:
#Q2

arr1,arr2 = (np.array(list(map(int,input().split()))) for i in range(2))
print()
print(np.concatenate((arr1,arr2)))
print()
print(np.sort(np.concatenate((arr1,arr2))))

10 2 8 4 6
1 9 3 7 5

[10  2  8  4  6  1  9  3  7  5]

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
#Q3

arr = np.arange(2,50,3).reshape(4,4)
print(arr.ndim,"dimensions")
print("size",np.shape(arr))

2 dimensions
size (4, 4)


In [50]:
#Q4

arr = np.arange(15).reshape(3,5)
print(arr[:, :, np.newaxis])
print()
print(np.expand_dims(arr,1))

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]]

[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]]


In [53]:
#Q5

arr3 = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])
arr4 = np.array([ [11,12,13] , [14,15,16] , [17,18,19] ])

print(np.vstack((arr3,arr4)))
print() 
print(np.hstack((arr3,arr4)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [57]:
#Q6

arr4 = np.array([ [11,12,13] , [16,19,11] , [12,13,19] ])
arr5=np.unique(arr4)
print(arr5)
print(arr5.size)

[11 12 13 16 19]
5
